import { expect, test, type Page } from '@playwright/test'
import { serviceWorkspace } from './service-workflow.fixture'

async function addCatalogItem(page: Page, kind: 'product' | 'service', name: string) {
  await page.getByRole('button', { name: kind === 'product' ? 'Add product' : 'Add service', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: `Add ${kind} ${name}`, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}

test.beforeEach(({ baseURL }) => {
  test.skip(!['localhost', '127.0.0.1'].includes(new URL(baseURL!).hostname), 'Controlled HTTP fixtures run only against the local web app.')
})

test('catalog supports page-long descriptions, cents and icon-only deletion', async ({ page }) => {
  const fixture = await serviceWorkspace(page)
  await page.goto('/dashboard/services')
  await expect(page.getByRole('heading', { level: 1, name: 'Service catalog' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Service status' })).toHaveCount(0)
  await page.getByRole('button', { name: 'New service' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Service name').fill('Full detailing')
  const description = dialog.getByLabel('Description')
  await expect(description).toHaveJSProperty('tagName', 'TEXTAREA')
  await expect(description).toHaveAttribute('rows', '10')
  await description.fill(fixture.longDescription)
  await dialog.getByLabel('Reference price').fill('12345')
  await expect(dialog.getByLabel('Reference price')).toHaveValue('123.45')
  await dialog.getByRole('button', { name: 'Create service' }).click()
  const row = page.getByRole('row').filter({ hasText: 'Full detailing' })
  await expect(row).toBeVisible()
  expect(fixture.offerings[1]?.description).toBe(fixture.longDescription.trim())
  expect(fixture.offerings[1]?.referencePrice).toBe(123.45)
  const remove = row.getByRole('button', { name: 'Delete service Full detailing' })
  await expect(remove).toHaveText('')
  await expect(row.getByRole('button', { name: 'Edit service Full detailing' })).toHaveText('')
  await remove.click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete service', exact: true }).click()
  await expect(row).toHaveCount(0)
})

test('quote approval opens execution, keeps the original quote and protects catalog deletion', async ({ page }) => {
  const fixture = await serviceWorkspace(page)
  await page.goto('/dashboard/estimates')
  await page.getByRole('button', { name: 'Create estimate' }).click()
  await page.getByLabel('Customer name').fill('Ana Silva')
  await page.getByLabel('Work description').fill('Oil and detailed cleaning')
  await page.locator('form').getByRole('button', { name: 'Create estimate' }).click()
  await expect(page).toHaveURL(/\/dashboard\/estimates\/order-1$/)
  await addCatalogItem(page, 'service', 'Detailed cleaning')
  await expect(page.getByLabel('Customer name')).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Edit details', exact: true })).toHaveCount(0)
  await page.getByLabel('Work description').fill('Oil and detailed cleaning, updated instructions')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save details', exact: true })).toHaveCount(0)
  await expect(page.locator('fieldset').getByText('Detailed cleaning', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save estimate' }).click()
  await expect(page.getByRole('button', { name: 'Approve estimate' })).toBeEnabled()
  await page.getByRole('button', { name: 'Approve estimate' }).click()
  await expect(page).toHaveURL(/\/dashboard\/service-orders\/order-1$/)
  await expect(page.getByRole('link', { name: /^Services/ })).toContainText('1')
  await expect(page.getByLabel('Customer name')).toBeEnabled()
  await page.getByLabel('Customer name').fill('Temporary customer')
  await page.getByRole('button', { name: 'Cancel editing', exact: true }).click()
  await expect(page.getByLabel('Customer name')).toHaveValue('Ana Silva')
  await page.getByRole('button', { name: 'Start work' }).click()
  await expect(page.getByText('In progress', { exact: true })).toBeVisible()

  await page.goto('/dashboard/services')
  await page.getByRole('button', { name: 'Delete service Detailed cleaning' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete service', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('This service is used by open quotes or services.')
  await page.getByRole('alert').getByRole('link', { name: /Ana Silva/ }).click()
  await expect(page).toHaveURL(/\/dashboard\/service-orders\/order-1$/)

  await page.getByRole('button', { name: 'Edit additional work' }).click()
  await page.getByRole('button', { name: 'Add service', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Add one-off labor' }).click()
  await page.getByLabel('Item name').fill('Unexpected panel repair')
  await page.locator('fieldset summary').click()
  await page.getByLabel('Full description').fill('Repair damaged panel discovered during cleaning.')
  await page.getByRole('textbox', { name: 'Unit price' }).fill('2500')
  await page.getByRole('button', { name: 'Request client approval' }).click()
  await expect(page.getByRole('button', { name: 'Close order and record sale' })).toBeDisabled()
  await page.getByRole('button', { name: 'Confirm client approval' }).click()
  expect(fixture.orders[0]?.acceptedQuote?.[0]?.unitPrice).toBe(102.5)
  await page.getByRole('button', { name: 'Close order and record sale' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Close order and record sale' }).click()
  await expect(page.getByText('Linked sale: #sale-1')).toBeVisible()
  expect(fixture.orders[0]?.sale?.total).toBe(127.5)

  await page.goto('/dashboard/services')
  await page.getByRole('button', { name: 'Delete service Detailed cleaning' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete service', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'Detailed cleaning' })).toHaveCount(0)
  await page.goto('/dashboard/estimates/order-1')
  await expect(page.getByText('Detailed cleaning', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Approve estimate' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Start work' })).toHaveCount(0)
  await expect(page.getByText('Unexpected panel repair', { exact: true })).toHaveCount(0)
})

test('date filters and record actions fit on a narrow screen', async ({ page }) => {
  await serviceWorkspace(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/dashboard/estimates')
  await expect(page.getByLabel('Due date')).toBeVisible()
  const date = await page.getByLabel('Due date').boundingBox()
  expect(date!.x + date!.width).toBeLessThanOrEqual(390)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

for (const width of [390, 1366, 1920]) {
  test(`populated quotes and services keep actions inside the panel at ${width}px`, async ({ page }) => {
    const fixture = await serviceWorkspace(page)
    const item = { kind: 'SERVICE' as const, productId: null, serviceOfferingId: null, description: 'Detailed cleaning', details: 'Long details '.repeat(60), quantity: 1, unitPrice: 102.5 }
    fixture.orders.push({ id: 'order-1', establishmentId: 'tenant-1', customerName: 'Customer'.repeat(24), description: 'Description'.repeat(100), status: 'ORCADA', dueAt: '2026-10-10T12:00:00Z', responsibleId: null, completedAt: null, updatedAt: '2026-10-01T12:00:00Z', acceptedQuote: null, items: [item], events: [] })
    fixture.orders.push({ ...fixture.orders[0]!, id: 'order-2', customerName: 'Active'.repeat(24), status: 'EM_EXECUCAO', acceptedQuote: [item] })
    await page.setViewportSize({ width, height: 900 })
    for (const path of ['/dashboard/estimates', '/dashboard/service-orders']) {
      await page.goto(path)
      const record = page.getByRole('link', { name: /^ActiveActive/ }).first()
      await expect(record).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
      for (const action of await page.getByRole('link', { name: /^(Edit quote|View quote|View service) / }).all()) {
        const box = await action.boundingBox()
        expect(box!.x + box!.width).toBeLessThanOrEqual(width)
      }
    }
    await page.goto('/dashboard/estimates/order-1')
    await expect(page.getByLabel('Customer name')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await expect(page.getByRole('table', { name: 'Product', exact: true })).toHaveCount(0)
    await expect(page.getByRole('table', { name: 'Service', exact: true })).toHaveCount(0)
    await expect(page.locator('fieldset textarea')).toBeHidden()
    for (const kind of ['product', 'service'] as const) {
      await page.getByRole('button', { name: kind === 'product' ? 'Add product' : 'Add service', exact: true }).click()
      const dialog = page.getByRole('dialog')
      await expect(dialog.getByRole('button', { name: kind === 'product' ? 'Add product Motor oil' : 'Add service Detailed cleaning' })).toBeVisible()
      const box = await dialog.boundingBox()
      expect(box!.x).toBeGreaterThanOrEqual(0)
      expect(box!.x + box!.width).toBeLessThanOrEqual(width)
      expect(box!.height).toBeLessThanOrEqual(900)
      await page.keyboard.press('Escape')
      await expect(page.getByRole('dialog')).toHaveCount(0)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `/tmp/tozzo-quote-${width}.png`, fullPage: true })
    await page.goto('/dashboard/service-orders/order-2')
    await expect(page.getByLabel('Customer name')).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  })
}


test('product and service modals search descriptions and paginate independently', async ({ page }) => {
  const fixture = await serviceWorkspace(page)
  for (let i = 2; i <= 12; i++) {
    fixture.products.push({ id: `product-${i}`, name: `Part ${i}`, ingredients: `Material ${i}`, price: i })
    fixture.offerings.push({ id: `catalog-${i}`, establishmentId: 'tenant-1', name: `Repair ${i}`, description: `Procedure ${i}`, referencePrice: i })
  }
  fixture.orders.push({ id: 'order-1', establishmentId: 'tenant-1', customerName: 'Ana', description: 'Maintenance', status: 'ABERTA', dueAt: null, responsibleId: null, completedAt: null, updatedAt: '2026-10-01T12:00:00Z', acceptedQuote: null, items: [], events: [] })
  await page.goto('/dashboard/estimates/order-1')
  await expect(page.getByRole('table')).toHaveCount(0)
  await page.getByRole('button', { name: 'Add product', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Add product Motor oil' })).toBeVisible()
  await dialog.getByLabel('Search products').fill('lubricant')
  await expect(dialog.getByRole('button', { name: 'Add product Part 2', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Add product Motor oil' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Add service', exact: true }).click()
  await dialog.getByLabel('Search catalog services').fill('surface')
  await expect(dialog.getByRole('button', { name: 'Add service Repair 2', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Add service Detailed cleaning' }).click()
  await expect(page.getByLabel('Full description').first()).toHaveValue('Synthetic lubricant for engine maintenance')
  await page.getByRole('button', { name: 'Add product', exact: true }).click()
  await expect(dialog.getByLabel('Search products')).toHaveValue('lubricant')
  await dialog.getByLabel('Search products').fill('')
  await expect(dialog.getByRole('button', { name: 'Next', exact: true })).toBeEnabled()
  await dialog.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Add product Part 11' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Add service', exact: true }).click()
  await expect(dialog.getByLabel('Search catalog services')).toHaveValue('surface')
  await dialog.getByLabel('Search catalog services').fill('')
  await expect(dialog.getByRole('button', { name: 'Next', exact: true })).toBeEnabled()
  await dialog.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Add service Repair 11' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Add product', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Add product Part 11' })).toBeVisible()
  await page.keyboard.press('Escape')
  const firstItem = page.locator('fieldset').first()
  await expect(firstItem.getByLabel('Full description')).toBeHidden()
  await firstItem.locator('summary').click()
  await firstItem.getByLabel('Full description').fill('Updated lubricant instructions')
  await firstItem.locator('summary').click()
  await expect(firstItem.getByLabel('Full description')).toBeHidden()
  await page.getByRole('button', { name: 'Save estimate' }).click()
  await expect(page.getByRole('button', { name: 'Approve estimate' })).toBeEnabled()
  expect(fixture.orders[0]?.items[0]?.details).toBe('Updated lubricant instructions')
})

test('quote additions work without crypto.randomUUID', async ({ page }) => {
  const fixture = await serviceWorkspace(page)
  await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', { value: undefined, configurable: true }))
  fixture.orders.push({ id: 'order-1', establishmentId: 'tenant-1', customerName: 'Ana', description: 'Maintenance', status: 'ABERTA', dueAt: null, responsibleId: null, completedAt: null, updatedAt: '2026-10-01T12:00:00Z', acceptedQuote: null, items: [], events: [] })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/dashboard/estimates/order-1')
  await addCatalogItem(page, 'product', 'Motor oil')
  await addCatalogItem(page, 'service', 'Detailed cleaning')
  await page.getByRole('button', { name: 'Add service', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Add one-off labor' }).click()
  await page.getByLabel('Item name').fill('Emergency repair')
  await expect(page.locator('fieldset')).toHaveCount(3)
  await page.getByRole('button', { name: 'Save estimate' }).click()
  await expect(page.getByRole('button', { name: 'Approve estimate' })).toBeEnabled()
  expect(fixture.orders[0]?.items).toHaveLength(3)
  expect(errors).toEqual([])
})
