name: deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              cd /home/victor/app/frontend
              git pull origin main
              cd ..
              docker compose up -d --build --force-recreate frontend
            else
              cd /home/victor/dev-app/frontend
              git pull origin dev
              cd ..
              docker compose up -d --build --force-recreate frontend
            fi